# These are subject to update via CI
image:
  digest: iMg-digest

source:
  branch: dev
  commit: 2019-11-29T20:55:00Z-commit
  repository: github.com/aginfo/agrible-platform-tools
  shortCommit: Sht-commit
  version: "1.1.3"


# Static values
namespace: ci-cd-demo-test
replicas: 2
