# These are subject to update via CI
image:
  digest: IMG-DIG

source:
  branch: MM-ABC
  commit: 2019-11-27T22:50:48Z-commit
  repository: github.com/aginfo/agrible-platform-tools
  shortCommit: sht-cOMMIt
  version: "IMG-DIG"


# Static values
namespace: ci-cd-demo-test
replicas: 2
