# See https://circleci.com/docs/2.0/configuration-reference/
version: 2.1



jobs:
  build-and-push-image:
    # See https://circleci.com/docs/2.0/executor-types/#using-machine
    # Here we need to use a VM as we need access to the docker daemon, could find no DIND at https://circleci.com/docs/2.0/circleci-images/
    machine:
      image: ubuntu-1604:201903-01
    steps:
    - checkout
    - run:
        name: Build
        command: |
          git branch -a
          git remote -v
          cat ~/.gitconfig
          docker image ls
          docker build -t ted:1.0 .
          docker image ls
    - run:
        name: Push
        command: |
          docker image ls



workflows:
  build-and-push-image:
    jobs:
    - build-and-push-image:
        filters:
          # Only allow from this point on for the master branch
          branches:
            only:
            - master
