# See https://circleci.com/docs/2.0/configuration-reference/
version: 2.1



references:
  # See https://circleci.com/docs/2.0/executor-types/#using-machine
  # Here we need to use a VM as we need access to the docker daemon, could find no DIND at https://circleci.com/docs/2.0/circleci-images/
  host-config: &host-config
    machine:
    - image: ubuntu-1604:201903-01



jobs:
  j-1:
     <<: *machine-config
    steps:
    - checkout
    - run:
        name: Git info
        command: |
          git branch -a
          git remote -v
          cat ~/.gitconfig
          docker image ls
          docker build -t ted:1.0 .
          docker image ls


workflows:
  wf-1:
    jobs:
    - j-1:
        filters:
          # Only allow from this point on for the master branch
          branches:
            only:
            - master
