{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    {{- include "ci-cd-demo.labels" . | nindent 4 }}
  name: {{ include "ci-cd-demo.serviceAccountName" . }}
  namespace: {{ .Values.namespace }}
{{- end -}}
